# Generated by Django 4.0.3 on 2022-10-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
            ],
            bases=('accounts.profile',),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
