# Generated by Django 4.0.3 on 2022-10-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profiles_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='profile_image'),
        ),
    ]
