# Generated by Django 4.1.1 on 2022-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('MOBILE', 'MOBILE'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50),
        ),
    ]
