# Generated by Django 4.1.1 on 2022-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_original',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
