# Generated by Django 4.1.1 on 2022-10-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
